syntax = "proto3";

package mainpg;

option go_package = "proto/gen;genpb";

service Calculator {
    rpc GenerateFibonacci(FibonacciRequest) returns (stream FibonacciResponse); // Server-side streaming RPC
    rpc SendNumbers (stream NumberRequest) returns (NumberResponse); // Client-side streaming RPC
    rpc Chat (stream ChatMessage) returns (stream ChatMessage); // Bi-directional streaming RPC
}

message FibonacciRequest {
    int32 N = 1;
}

message FibonacciResponse {
    int32 Number = 1;
}

message NumberRequest {
    int32 Number = 1;
}

message NumberResponse {
    int32 Sum = 1;
}

message ChatMessage {
    string Message = 1;
}   
